<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationWithAdvert($limit){
        $qb = $this->createQueryBuilder('a')->innerJoin('a.advert','advert')
            ->addSelect('advert');
        $qb->setMaxResults($limit);
        return $qb->getQuery()->getResult();

    }
}
